sudo: false

language: scala
jdk: oraclejdk8

matrix:
  include:
    - scala: 2.10.7
      env: TRAVIS_SBT_VERSION="0.13.16"
    - scala: 2.12.4
      env: TRAVIS_SBT_VERSION="1.0.3"

script:
  - (cd sbt-cross && sbt "++${TRAVIS_SCALA_VERSION}" "^^${TRAVIS_SBT_VERSION}" 'all package test')

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
